CREATE TABLE IF NOT EXISTS aqi_features (
    city TEXT NOT NULL,
    datetime TIMESTAMPTZ NOT NULL,
    pm10 DOUBLE PRECISION,
    pm2_5 DOUBLE PRECISION,
    carbon_monoxide DOUBLE PRECISION,
    nitrogen_dioxide DOUBLE PRECISION,
    sulphur_dioxide DOUBLE PRECISION,
    ozone DOUBLE PRECISION,
    us_aqi DOUBLE PRECISION,
    us_aqi_pm2_5 DOUBLE PRECISION,
    us_aqi_pm10 DOUBLE PRECISION,
    temperature_2m DOUBLE PRECISION,
    relative_humidity_2m DOUBLE PRECISION,
    surface_pressure DOUBLE PRECISION,
    wind_speed_10m DOUBLE PRECISION,
    wind_direction_10m DOUBLE PRECISION,
    -- Enhanced Atmospheric & Meteorological Columns
    precipitation DOUBLE PRECISION,
    cloud_cover DOUBLE PRECISION,
    dew_point_2m DOUBLE PRECISION,
    shortwave_radiation DOUBLE PRECISION,
    boundary_layer_height DOUBLE PRECISION,
    aerosol_optical_depth DOUBLE PRECISION,
    dust DOUBLE PRECISION,
    uv_index DOUBLE PRECISION,
    -- Temporal columns
    hour INT,
    day INT,
    month INT,
    day_of_week INT,
    is_weekend INT,
    -- Lag & rolling stats
    aqi_lag_24h DOUBLE PRECISION,
    aqi_lag_48h DOUBLE PRECISION,
    aqi_rolling_mean_3h DOUBLE PRECISION,
    aqi_rolling_mean_24h DOUBLE PRECISION,
    aqi_change_rate_24h DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (city, datetime)
);

ALTER TABLE aqi_features ADD COLUMN IF NOT EXISTS precipitation DOUBLE PRECISION;
ALTER TABLE aqi_features ADD COLUMN IF NOT EXISTS cloud_cover DOUBLE PRECISION;
ALTER TABLE aqi_features ADD COLUMN IF NOT EXISTS dew_point_2m DOUBLE PRECISION;
ALTER TABLE aqi_features ADD COLUMN IF NOT EXISTS shortwave_radiation DOUBLE PRECISION;
ALTER TABLE aqi_features ADD COLUMN IF NOT EXISTS boundary_layer_height DOUBLE PRECISION;
ALTER TABLE aqi_features ADD COLUMN IF NOT EXISTS aerosol_optical_depth DOUBLE PRECISION;
ALTER TABLE aqi_features ADD COLUMN IF NOT EXISTS dust DOUBLE PRECISION;
ALTER TABLE aqi_features ADD COLUMN IF NOT EXISTS uv_index DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS idx_aqi_features_city_datetime 
ON aqi_features (city, datetime DESC);

CREATE INDEX IF NOT EXISTS idx_aqi_features_datetime 
ON aqi_features (datetime DESC);

CREATE TABLE IF NOT EXISTS model_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name TEXT NOT NULL,
    version INT NOT NULL DEFAULT 1,
    avg_rmse DOUBLE PRECISION,
    metrics JSONB DEFAULT '{}'::jsonb,
    feature_names JSONB DEFAULT '[]'::jsonb,
    shap_summary JSONB DEFAULT '{}'::jsonb,
    storage_path TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_model_registry_name_version 
ON model_registry (model_name, version DESC);

ALTER TABLE aqi_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE model_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to aqi_features"
ON aqi_features FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update to aqi_features"
ON aqi_features FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read access to model_registry"
ON model_registry FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update to model_registry"
ON model_registry FOR ALL USING (true) WITH CHECK (true);
